# Generated by Django 5.2.1 on 2025-08-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('father_name', models.CharField(max_length=30)),
                ('mother', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('mo_no', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('village', models.CharField(max_length=100)),
            ],
        ),
    ]
