# Generated by Django 5.2.1 on 2025-08-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_date', models.DateField()),
                ('deseas', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=300)),
                ('notes', models.CharField(max_length=300)),
                ('bed_no', models.IntegerField(max_length=5)),
                ('gardian', models.CharField(max_length=50)),
            ],
        ),
    ]
